services:
  - type: web
    name: whatsapp-webjs-server
    env: node
    region: singapore
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SESSION_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
    autoDeploy: true
